ci/update-flake: continue on .#all-maintainers failure

diff --git a/.github/workflows/update-flake.yml b/.github/workflows/update-flake.yml
--- a/.github/workflows/update-flake.yml
+++ b/.github/workflows/update-flake.yml
@@ -63,11 +63,15 @@ jobs:
 
           # The nixpkgs maintainers may have changed, so keep all-maintainers
           # in sync
-          nix run .#all-maintainers
-
-          git add generated/all-maintainers.nix
-          git commit --message "stylix: update all-maintainers list" ||
-            echo "generated/all-maintainers.nix has no changes"
+          if nix run .#all-maintainers; then
+            git add generated/all-maintainers.nix
+            if ! git commit --message "stylix: update all-maintainers list";
+            then
+              echo "::debug::generated/all-maintainers.nix has no changes"
+            fi
+          else
+            echo "::error::failed to update generated/all-maintainers.nix"
+          fi
 
       - name: create pull request
         env:
